services:
  api:
    container_name: api
    restart: always
    build: .
    ports: 
      - 5000:5000
      - 9229:9229
    environment:
      PORT: 5000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/.pnpm-store
      - /usr/src/app/node_modules 
    command: pnpm dev